### ISSUE TITLE
[Backend] Add swagger documentation

### ISSUE THREAD

**Issue by sprakash57** [sprakash57/shortify#11]
Add Swagger docs for all the services. Please note that
- Documentation should adhere to OpenAPI v3 standards.
- There should be a UI to access those services.

**Comment by gazconroy** [comment]
If you're still interested, I'm happy to provide this. A couple of questions, though:

1. Is enabling Swagger UI's 'try it out' feature important to you? If so, the Swagger UI files either need to be hosted on the same server and port as the API or CORS support needs to be enabled. For more information, see https://swagger.io/docs/open-source-tools/swagger-ui/usage/cors/
2. This is more of an observation than a question about the API calls. Running the Dockeer container, I'd expected the shorty to be prefixed with localhost rather than https://sup.dev/. How to configure this to a specific domain?

**Comment by sprakash57** [comment]
Thanks for extending support.
1. No its not important and its not part of the scope for the ticket as of now. We just need to docs and ui locally.
2. I will get back to you with proper answer. If you have any suggestions, please go ahead and open an issue.
